server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Spring Boot 애플리케이션 로그
  - job_name: spring-boot-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot
          app: catch-app
          __path__: /app/logs/*.log
    
    pipeline_stages:
      - match:
          selector: '{job="spring-boot"}'
          stages:
            - regex:
                expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3})\s+(?P<level>[A-Z]+)\s+(?P<pid>\d+)\s+---\s+\[(?P<thread>.*?)\]\s+(?P<logger>.*?)\s+:\s+(?P<message>.*)'
            - labels:
                level:
                thread:
                logger:
            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05.000'
                location: 'Asia/Seoul'

  # 시스템 로그
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log